# Generated by Django 5.0.6 on 2026-08-27 23:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membresia',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Membresía', 'verbose_name_plural': 'Membresías'},
        ),
        migrations.AlterModelOptions(
            name='planmembresia',
            options={'ordering': ['nombre'], 'verbose_name': 'Plan de Membresía', 'verbose_name_plural': 'Planes de Membresía'},
        ),
        migrations.AlterField(
            model_name='planmembresia',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
