# Generated by Django 5.0.6 on 2026-09-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_membresia_textchoices_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='avisos_enviados',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
