# Generated by Django 5.1.4 on 2026-09-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_seed_expiration_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmembresia',
            name='es_popular',
            field=models.BooleanField(default=False),
        ),
    ]
