# Generated by Django 5.1.4 on 2026-09-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_gym', models.CharField(default='Winnie The Gym', max_length=100)),
                ('aforo_maximo', models.IntegerField(default=200)),
                ('hora_apertura', models.TimeField(default='07:00')),
                ('hora_cierre', models.TimeField(default='23:00')),
                ('telefono_contacto', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Configuración del Gimnasio',
                'verbose_name_plural': 'Configuración del Gimnasio',
            },
        ),
    ]
