# Generated by Django 5.0.6 on 2026-08-27 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0006_socio_numero_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('funcional', 'Funcional'), ('spinning', 'Spinning'), ('crossfit', 'Crossfit'), ('pilates', 'Pilates'), ('yoga', 'Yoga'), ('boxeo', 'Boxeo'), ('hiit', 'HIIT')], default='funcional', max_length=50)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('dia', models.CharField(default='Lunes', max_length=20)),
                ('hora', models.CharField(default='08:00', max_length=10)),
                ('duracion_min', models.PositiveIntegerField(default=45)),
                ('sala', models.CharField(default='Sala A', max_length=80)),
                ('instructor', models.CharField(default='Carlos R.', max_length=120)),
                ('cupo_maximo', models.PositiveIntegerField(default=20)),
                ('lista_espera_max', models.PositiveIntegerField(default=5)),
                ('cancelacion_horas', models.PositiveIntegerField(default=2)),
                ('planes_habilitados', models.JSONField(blank=True, default=list)),
                ('recurrencia', models.CharField(default='Semanal - L/M/V', max_length=100)),
                ('dias_recurrencia', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='activa', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistio', models.BooleanField(default=False)),
                ('en_espera', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='classes.clase')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_clases', to='members.socio')),
            ],
            options={
                'verbose_name': 'Inscripción a Clase',
                'verbose_name_plural': 'Inscripciones a Clases',
                'unique_together': {('clase', 'socio')},
            },
        ),
    ]
