# Generated by Django 5.0.6 on 2026-08-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_clase_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='instructor',
            field=models.CharField(default='', max_length=120),
        ),
    ]
