# Generated by Django 5.1.4 on 2026-09-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_inscripcionclase_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
