# Generated by Django 5.0.6 on 2026-08-27 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_socio_numero_not_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socio',
            options={'ordering': ['numero_socio'], 'verbose_name': 'Socio', 'verbose_name_plural': 'Socios'},
        ),
    ]
