# Generated by Django 5.0.6 on 2026-09-11 02:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0007_socio_textchoices_ordering'),
        ('memberships', '0004_seed_expiration_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('moneda', models.CharField(default='ARS', max_length=3)),
                ('metodo', models.CharField(choices=[('mercado_pago', 'MercadoPago'), ('manual', 'Cobro Manual')], default='mercado_pago', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('mp_preference_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('mp_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mp_external_reference', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('mp_status_detail', models.CharField(blank=True, default='', max_length=100)),
                ('raw_webhook', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('membresia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='memberships.membresia')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='memberships.planmembresia')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='members.socio')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['socio', 'estado'], name='pagos_socio_e_idx'), models.Index(fields=['mp_external_reference'], name='pagos_extref_idx')],
            },
        ),
    ]
