# Generated by Django 5.0.6 on 2026-08-10 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
                ('access_type', models.CharField(choices=[('ENTRY', 'Ingreso'), ('EXIT', 'Egreso')], default='ENTRY', max_length=10, verbose_name='Tipo de Acceso')),
                ('status', models.CharField(choices=[('GRANTED', 'Permitido'), ('DENIED', 'Denegado')], default='GRANTED', max_length=10, verbose_name='Estado de Acceso')),
                ('denial_reason', models.CharField(blank=True, choices=[('TOKEN_EXPIRED', 'Token QR expirado'), ('INVALID_SIGNATURE', 'Firma de token inválida'), ('REPLAY_ATTACK', 'Token QR ya utilizado'), ('MEMBERSHIP_INACTIVE', 'Membresía inactiva o cuota vencida'), ('NO_MEMBERSHIP', 'Socio sin membresía registrada'), ('USER_SUSPENDED', 'Usuario suspendido'), ('UNKNOWN_USER', 'Usuario no registrado')], max_length=50, null=True, verbose_name='Motivo de Rechazo')),
                ('qr_jti', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Identificador Unico del QR (JTI)')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Escaneado por (Personal/Dispositivo)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'ordering': ['-timestamp'],
            },
        ),
    ]
