# Generated by Django 5.0.6 on 2026-08-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='denial_reason',
            field=models.CharField(blank=True, choices=[('TOKEN_EXPIRED', 'Token QR expirado'), ('INVALID_SIGNATURE', 'Firma de token inválida'), ('INVALID_TOKEN', 'Token QR malformado o sin identificador'), ('REPLAY_ATTACK', 'Token QR ya utilizado'), ('MEMBERSHIP_INACTIVE', 'Membresía inactiva o cuota vencida'), ('NO_MEMBERSHIP', 'Socio sin membresía registrada'), ('USER_SUSPENDED', 'Usuario suspendido'), ('UNKNOWN_USER', 'Usuario no registrado')], max_length=50, null=True, verbose_name='Motivo de Rechazo'),
        ),
    ]
